export interface Question {
  id: string;
  title: string;
  hint?: string;
  type: "text" | "date" | "radio" | "select" | "email" | "tel";
  options?: string[];
  required?: boolean;
}

export const QUESTIONS: Question[] = [
  {
    id: "givenNames",
    title: "What is your given name(s)?",
    hint: "Enter your given names as they appear on your passport",
    type: "text",
    required: true,
  },
  {
    id: "surname",
    title: "What is your surname or family name?",
    hint: "Enter your family name as it appears on your passport",
    type: "text",
    required: true,
  },
  {
    id: "dateOfBirth",
    title: "What is your date of birth?",
    hint: "For example, 31 03 1990",
    type: "date",
    required: true,
  },
  {
    id: "sex",
    title: "What is your sex?",
    hint: "Select the sex shown on your passport",
    type: "radio",
    options: ["Male", "Female"],
    required: true,
  },
  {
    id: "nationality",
    title: "What is your nationality?",
    hint: "Select your nationality as shown on your passport",
    type: "select",
    options: [
      "",
      "Afghan",
      "Albanian",
      "Algerian",
      "American",
      "Argentinian",
      "Australian",
      "Austrian",
      "Bangladeshi",
      "Belgian",
      "Bolivian",
      "Brazilian",
      "British",
      "Bulgarian",
      "Cambodian",
      "Canadian",
      "Chilean",
      "Chinese",
      "Colombian",
      "Croatian",
      "Cuban",
      "Czech",
      "Danish",
      "Dutch",
      "Egyptian",
      "Estonian",
      "Ethiopian",
      "Filipino",
      "Finnish",
      "French",
      "German",
      "Greek",
      "Hungarian",
      "Indian",
      "Indonesian",
      "Iranian",
      "Iraqi",
      "Irish",
      "Israeli",
      "Italian",
      "Japanese",
      "Jordanian",
      "Kenyan",
      "Korean",
      "Kuwaiti",
      "Latvian",
      "Lebanese",
      "Lithuanian",
      "Malaysian",
      "Mexican",
      "Moroccan",
      "Nepalese",
      "New Zealander",
      "Nigerian",
      "Norwegian",
      "Pakistani",
      "Peruvian",
      "Polish",
      "Portuguese",
      "Romanian",
      "Russian",
      "Saudi Arabian",
      "Serbian",
      "Singaporean",
      "Slovakian",
      "Slovenian",
      "South African",
      "Spanish",
      "Sri Lankan",
      "Swedish",
      "Swiss",
      "Syrian",
      "Taiwanese",
      "Thai",
      "Turkish",
      "Ukrainian",
      "Emirati",
      "Venezuelan",
      "Vietnamese",
      "Yemeni",
      "Zimbabwean",
    ],
    required: true,
  },
  {
    id: "passportNumber",
    title: "What is your passport number?",
    hint: "Enter the passport number exactly as it appears on your passport",
    type: "text",
    required: true,
  },
  {
    id: "dateOfIssue",
    title: "When was your passport issued?",
    hint: "For example, 15 06 2020",
    type: "date",
    required: true,
  },
  {
    id: "dateOfExpiry",
    title: "When does your passport expire?",
    hint: "For example, 14 06 2030",
    type: "date",
    required: true,
  },
  {
    id: "email",
    title: "What is your email address?",
    hint: "We will use this to send you updates about your application",
    type: "email",
    required: true,
  },
  {
    id: "phone",
    title: "What is your phone number?",
    hint: "Include the country code, for example +44 7700 900000",
    type: "tel",
    required: false,
  },
  {
    id: "biometricsCountry",
    title: "Select a country to provide your biometrics",
    hint: "To complete your application, you must provide your biometrics (fingerprints and facial photograph). This may involve attending a visa application centre (VAC) operated by one of our commercial partners.\n\nWe need to know which commercial partner will manage your biometrics appointment. This is so we can transfer you to the correct website after you have submitted your visa application.\n\nEnter the country where you would like to provide your biometrics. This will usually be the country you are in now. If there is no VAC in your selected country, you will be able to choose an alternative location.\n\nIf you believe you are unable to provide your biometrics at any location, you should still choose a location. You will then be told how to proceed.",
    type: "text",
    required: true,
  },
];

// Mock data for auto-fill demo
export const MOCK_ANSWERS: Record<string, string> = {
  givenNames: "ZHANG WEI",
  surname: "ZHANG",
  dateOfBirth: "1990-05-15",
  sex: "Male",
  nationality: "Chinese",
  passportNumber: "E12345678",
  dateOfIssue: "2020-01-10",
  dateOfExpiry: "2030-01-09",
  email: "zhang.wei@example.com",
  phone: "+86 138 0000 1234",
  biometricsCountry: "China",
};
